
BLENDER="C:\Program Files\Blender Foundation\Blender 4.2\blender.exe"
DIST=../dist

all : \
    $(DIST)/forest_map.pnct \
    $(DIST)/forest_map.scene \

$(DIST)/forest_map.scene : forest_map.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "forest_map.blend:Main" "$(DIST)/forest_map.scene"

$(DIST)/forest_map.pnct : forest_map.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "forest_map.blend:Main" "$(DIST)/forest_map.pnct" 
